# Numbers.

Final calculations, tabulations, and mathemagic for the Artificial Intelligence Project Report.

In [30]:
%run analysis.py

To plot, execute the following:
from matplotlib import pyplot as mplt
from pandas.tools.plotting import parallel_coordinates
from scipy import stats

import seaborn as sns
sns.set_palette('muted')
sns.set_style('ticks')
sns.set_context('notebook')

In [31]:
results = pd.read_csv(combined_f)

# Rename select attributes
results['algo'] = results['algo'].apply(lambda x: 'A*' if (x=='astar') else 'IDA')

# preview changes
results.head(2)

  boardID algo                   heur size  expanded  branching  time  cost
0   1.txt   A*  disjointPDBHorizontal  3x3         1        2.0  4893     1
1   2.txt   A*  disjointPDBHorizontal  3x3         1        2.0  4814     1

In [35]:
# Number of experiments
grouping = ['algo', 'size', 'heur', 'boardID']
num_exps = results[grouping].groupby(grouping[:-1]).count()

# Rename for publication
num_exps.columns = ['Number Trials']
num_exps.index.names = ['Algorithm', 'Heuristic', 'Size']

num_exps

                                           Number Trials
Algorithm Heuristic Size
A*        3x3       NMaxSwap                         426
                    disjointPDBHorizontal            426
                    disjointPDBMax                   426
                    disjointPDBVertical              426
                    linearConflict                   426
                    manhattan                        426
                    nonAdditiveFringe                426
                    nonAdditiveMax                   426
          4x4       NMaxSwap                         440
                    disjointPDBHorizontal             84
                    disjointPDBMax                    83
                    disjointPDBVertical               84
                    linearConflict                   441
                    manhattan                        441
                    nonAdditiveFringe                 84
                    nonAdditiveMax                    84
IDA       3x3       linearConflict                   426
          4x4       linearConflict                   441

In [36]:
# filter and write out the 
num_8 = num_exps.iloc[num_exps.index.get_level_values('Size') == '3x3']
num_15 = num_exps.iloc[num_exps.index.get_level_values('Size') == '4x4']

num_8.to_latex('8-puzzle-number.tex')
num_15.to_latex('8-puzzle-number.tex')

In [37]:
num_8.to_latex((canonical_dir + '8-puzzle-number.tex'))
num_15.to_latex((canonical_dir + '8-puzzle-number.tex'))

### Descriptive Statistics

Mean, min/max, range, std deviations, etc.

In [40]:
d_stats = results.groupby(grouping[:-1]).describe()

In [45]:
d_stats.style.highlight_min(axis='columns')